server:
  port: 9999
zuul:
#  prefix: /fundoo
#  ignored-services: '*'
  routes:
    noteapplication:
      path: /noteapplication/**
      serviceId: noteservice
    userapplication:
      path: /userapplication/**
      serviceId: userservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: zuul